
# code for generating plots of simulated data from the Rstan models
# from the 'model.R' code

#--------------------------------------------------------------#
#--------------------------------------------------------------#

# Data
comb.df <- read.csv("data/simulation_data_all.csv", header = TRUE) 
# this .csv file is generated by 'simulation_plots_full.R'


# Plotting 

library(ggplot2)
library(viridis)
library(RColorBrewer)

df.eq <- data.frame(b_h = seq(from = 0, to = 3, by = 0.5), 
                    b_c = seq(from = 0, to = 3, by = 0.5))


# New facet label names for dose variable
hist.labs <- c("N. Historical = 1", "N. Historical = 2", "N. Historical = 3")
names(hist.labs) <- c("1", "2", "3")

# New facet label names for supp variable
alpha.labs <- c("alpha = 0.1", 
                "alpha = 0.5",
                "alpha = 1")
names(alpha.labs) <- c("0.1", "0.5", "1")

pp_15 <- 
  comb.df %>%
  filter(n_strike==15, alpha.val %in% c(0.1, 0.5, 1)) %>%
  ggplot(data = ., aes(x = b_h, y = b_c, fill = post_bias_det95), 
         color="black")+
  geom_tile(color = "black", alpha = 0.9)+
  geom_rect(data = df.eq, aes (xmin = -0.25, xmax = 0.25, 
                               ymin = -0.25, ymax = 0.25),
            color = "black", lwd = 1.2,
            fill = "transparent")+
  coord_equal()+
  geom_text(aes(label = round(post_bias_det95, 2), color = post_bias_det95), 
            size = 2.3, fontface = "bold")+
  scale_color_gradient2(low = "grey35",mid = "grey55", 
                        high = "white", guide = "none")+
  scale_fill_viridis("Bias Detection Rate",direction=-1,
                     option = "inferno", limits = c(0, 1))+
  scale_x_continuous(breaks = c(0:3), expand = c(0,0))+
  scale_y_continuous(breaks = c(0:3), expand = c(0,0))+
  facet_grid(n_h~alpha.val, labeller = labeller(n_h = hist.labs, 
                                                alpha.val = alpha.labs))+
  theme_classic()+
  xlab("Historical Bias")+
  ylab("Current Bias")+
  ggtitle("N Strike = 15")+
  theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        legend.position = "bottom")




pp_10 <- 
  comb.df %>%
  filter(n_strike==10, alpha.val %in% c(0.1, 0.5, 1)) %>%
  ggplot(data = ., aes(x = b_h, y = b_c, fill = post_bias_det95), 
         color="black")+
  geom_tile(color = "black", alpha = 0.9)+
  geom_rect(data = df.eq, aes (xmin = -0.25, xmax = 0.25, 
                               ymin = -0.25, ymax = 0.25),
            color = "black", lwd = 1.2,
            fill = "transparent")+
  coord_equal()+
  geom_text(aes(label = round(post_bias_det95, 2), color = post_bias_det95), 
            size = 2.3, fontface = "bold")+
  scale_color_gradient2(low = "grey35",mid = "grey55", 
                        high = "white", guide = "none")+
  scale_fill_viridis("Bias Detection Rate",direction=-1,
                     option = "inferno", limits = c(0, 1))+
  scale_x_continuous(breaks = c(0:3), expand = c(0,0))+
  scale_y_continuous(breaks = c(0:3), expand = c(0,0))+
  facet_grid(n_h~alpha.val, labeller = labeller(n_h = hist.labs, 
                                                alpha.val = alpha.labs))+
  theme_classic()+
  xlab("Historical Bias")+
  ylab("Current Bias")+
  ggtitle("N Strike = 10")+
  theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        legend.position = "bottom")


pp_6 <- 
  comb.df %>%
  filter(n_strike==6, alpha.val %in% c(0.1, 0.5, 1)) %>%
  ggplot(data = ., aes(x = b_h, y = b_c, fill = post_bias_det95), 
         color="black")+
  geom_tile(color = "black", alpha = 0.9)+
  geom_rect(data = df.eq, aes (xmin = -0.25, xmax = 0.25, 
                               ymin = -0.25, ymax = 0.25),
            color = "black", lwd = 1.2,
            fill = "transparent")+
  coord_equal()+
  geom_text(aes(label = round(post_bias_det95, 2), color = post_bias_det95), 
            size = 2.3, fontface = "bold")+
  scale_color_gradient2(low = "grey35",mid = "grey55", 
                        high = "white", guide = "none")+
  scale_fill_viridis("Bias Detection Rate",direction=-1,
                     option = "inferno", limits = c(0, 1))+
  scale_x_continuous(breaks = c(0:3), expand = c(0,0))+
  scale_y_continuous(breaks = c(0:3), expand = c(0,0))+
  facet_grid(n_h~alpha.val, labeller = labeller(n_h = hist.labs, 
                                                alpha.val = alpha.labs))+
  theme_classic()+
  xlab("Historical Bias")+
  ylab("Current Bias")+
  ggtitle("N Strike = 6")+
  theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        legend.position = "bottom", 
        legend.title.align = -0.5)


ggsave(plot = pp_15, filename = "pp15_95CI.png", height = 8, width = 8, 
       units = "in", dpi = 300)

ggsave(plot = pp_10, filename = "pp10_95CI.png", height = 8, width = 8, 
       units = "in", dpi = 300)

ggsave(plot = pp_6, filename = "pp6_95CI.png", height = 8, width = 8, 
       units = "in", dpi = 300)
