# New simulations - March 2022

#-------------------------------------------------------------------------------#



#-------------------------------------------------------------------------------#

library(dplyr)
library(tidyr)
library(stringr)
library(cowplot)




# STEPS

##STEP1 -  load and reformat output generated by 'model.R' code
##STEP2 -  combine all into data frame for plotting
##STEP3 - plot in ggplot2


d0_1 <- load('data/01.RData') 
d0_2 <- load('data/02.RData')

#i=1
for (i in 1:63){
  
  assign(paste("d0", paste("p", i, sep = ""), sep = "_"),
         eval(as.symbol(paste("p", i, sep = ""))))
  
}



# create holding DF
out.df.d0 <-  data.frame(
  iter = rep(paste("p", 1:63, sep = ""), each = 11),
  b_c = 0,
  b_h = rep(c(rep(0, 11), rep(0.5, 11), rep(1, 11), rep(1.5, 11),
              rep(2, 11), rep(2.5, 11), rep(3, 11)), 9),
  n_h = rep(c(rep(1, 77),rep(2, 77), rep(3, 77)), 3),
  alpha = rep(1:11, 63),
  n_strike = c(rep(6, 231), rep(10, 231), rep(15, 231))
)

get_p_results<-function(p,num_alphas)
{
  res=data.frame("post_bias"=rep(NA,num_alphas),
                 "post_mean"=rep(NA,num_alphas),
                 "post_sd"=rep(NA,num_alphas),
                 "post_bias_det80"=rep(NA,num_alphas),
                 "cp_80"=rep(NA,num_alphas),
                 "post_bias_det90"=rep(NA,num_alphas),
                 "cp_90"=rep(NA,num_alphas),
                 "post_bias_det95"=rep(NA,num_alphas),
                 "cp_95"=rep(NA,num_alphas))
  for(i in 1:11)
  {
    res[i,"post_bias"]<-as.numeric(p[[i]][[1]]["post_bias"])
    res[i,"post_mean"]<-as.numeric(p[[i]][[1]]["post_mean"])
    res[i,"post_sd"]<-as.numeric(p[[i]][[1]]["post_sd"])
    res[i,"post_bias_det80"]<-as.numeric(p[[i]][[1]]["post_bias_det80"])
    res[i,"cp_80"]<-as.numeric(p[[i]][[1]]["cp_80"])
    res[i,"post_bias_det90"]<-as.numeric(p[[i]][[1]]["post_bias_det90"])
    res[i,"cp_90"]<-as.numeric(p[[i]][[1]]["cp_90"])
    res[i,"post_bias_det95"]<-as.numeric(p[[i]][[1]]["post_bias_det95"])
    res[i,"cp_95"]<-as.numeric(p[[i]][[1]]["cp_95"])
  }
  return(res)
}

# create list of results
whichd="d0"
res.l<- list()
for (j in 1:63){
  iter.ind <- paste(paste(whichd, "p", sep = "_"), j, sep = "")
  iter.ls <- eval(as.symbol(iter.ind))
  print(iter.ind)
  res.l[[j]] <- get_p_results(p = iter.ls,
                              num_alphas = 11)
}

# convert to df
names(res.l) <- paste(paste(whichd, "p", sep = "_"), 1:63, sep = "")
res.l[["d0_p3"]]
res.df <- do.call(rbind.data.frame, res.l)

# combine with holding df
d0.df <- cbind(out.df.d0, res.df)


#---------------------------------#
# 0.5


d0.5_1 <- load('data/_.5_1.RData')
d0.5_2 <- load('data/_.5_2.RData')

# relabel p objects
for (i in 1:63){
  
  assign(paste("d0.5", paste("p", i, sep = ""), sep = "_"), 
         eval(as.symbol(paste("p", i, sep = ""))))
  
}



# create holding DF
out.df.d0.5 <-  data.frame(
  iter = rep(paste("p", 1:63, sep = ""), each = 11),
  b_c = 0.5,
  b_h = rep(c(rep(0, 11), rep(0.5, 11), rep(1, 11), rep(1.5, 11), 
              rep(2, 11), rep(2.5, 11), rep(3, 11)), 9),
  n_h = rep(c(rep(1, 77),rep(2, 77), rep(3, 77)), 3),
  alpha = rep(1:11, 63),
  n_strike = c(rep(6, 231), rep(10, 231), rep(15, 231))
)

get_p_results<-function(p,num_alphas)
{
  res=data.frame("post_bias"=rep(NA,num_alphas),
                 "post_mean"=rep(NA,num_alphas),
                 "post_sd"=rep(NA,num_alphas),
                 "post_bias_det80"=rep(NA,num_alphas),
                 "cp_80"=rep(NA,num_alphas),
                 "post_bias_det90"=rep(NA,num_alphas),
                 "cp_90"=rep(NA,num_alphas),
                 "post_bias_det95"=rep(NA,num_alphas),
                 "cp_95"=rep(NA,num_alphas))
  for(i in 1:11)
  {
    res[i,"post_bias"]<-as.numeric(p[[i]][[1]]["post_bias"])
    res[i,"post_mean"]<-as.numeric(p[[i]][[1]]["post_mean"])
    res[i,"post_sd"]<-as.numeric(p[[i]][[1]]["post_sd"])
    res[i,"post_bias_det80"]<-as.numeric(p[[i]][[1]]["post_bias_det80"])
    res[i,"cp_80"]<-as.numeric(p[[i]][[1]]["cp_80"])
    res[i,"post_bias_det90"]<-as.numeric(p[[i]][[1]]["post_bias_det90"])
    res[i,"cp_90"]<-as.numeric(p[[i]][[1]]["cp_90"])
    res[i,"post_bias_det95"]<-as.numeric(p[[i]][[1]]["post_bias_det95"])
    res[i,"cp_95"]<-as.numeric(p[[i]][[1]]["cp_95"])
  }
  return(res)
}

# create list of results
res.l<- list()
whichd  = "d0.5"
for (j in 1:63){
  iter.ind <- paste(paste(whichd, "p", sep = "_"), j, sep = "")
  iter.ls <- eval(as.symbol(iter.ind))
  print(iter.ind)
  res.l[[j]] <- get_p_results(p = iter.ls,
                              num_alphas = 11)
}

# convert to df
names(res.l) <- paste(paste(whichd, "p", sep = "_"), 1:63, sep = "") 
res.l[["d0.5_p3"]]
res.df <- do.call(rbind.data.frame, res.l)

# combine with holding df
d0.5.df <- cbind(out.df.d0.5, res.df)
#d0.5.df %>% View()

#---------------------------------#
# 1


d1_1 <- load('data/1_1.RData')
d1_2 <- load('data/1_2.RData')

# relabel p objects
for (i in 1:63){
  
  assign(paste("d1", paste("p", i, sep = ""), sep = "_"), 
         eval(as.symbol(paste("p", i, sep = ""))))
  
}



# create holding DF
out.df.d1 <-  data.frame(
  iter = rep(paste("p", 1:63, sep = ""), each = 11),
  b_c = 1,
  b_h = rep(c(rep(0, 11), rep(0.5, 11), rep(1, 11), rep(1.5, 11), 
              rep(2, 11), rep(2.5, 11), rep(3, 11)), 9),
  n_h = rep(c(rep(1, 77),rep(2, 77), rep(3, 77)), 3),
  alpha = rep(1:11, 63),
  n_strike = c(rep(6, 231), rep(10, 231), rep(15, 231))
)

get_p_results<-function(p,num_alphas)
{
  res=data.frame("post_bias"=rep(NA,num_alphas),
                 "post_mean"=rep(NA,num_alphas),
                 "post_sd"=rep(NA,num_alphas),
                 "post_bias_det80"=rep(NA,num_alphas),
                 "cp_80"=rep(NA,num_alphas),
                 "post_bias_det90"=rep(NA,num_alphas),
                 "cp_90"=rep(NA,num_alphas),
                 "post_bias_det95"=rep(NA,num_alphas),
                 "cp_95"=rep(NA,num_alphas))
  for(i in 1:11)
  {
    res[i,"post_bias"]<-as.numeric(p[[i]][[1]]["post_bias"])
    res[i,"post_mean"]<-as.numeric(p[[i]][[1]]["post_mean"])
    res[i,"post_sd"]<-as.numeric(p[[i]][[1]]["post_sd"])
    res[i,"post_bias_det80"]<-as.numeric(p[[i]][[1]]["post_bias_det80"])
    res[i,"cp_80"]<-as.numeric(p[[i]][[1]]["cp_80"])
    res[i,"post_bias_det90"]<-as.numeric(p[[i]][[1]]["post_bias_det90"])
    res[i,"cp_90"]<-as.numeric(p[[i]][[1]]["cp_90"])
    res[i,"post_bias_det95"]<-as.numeric(p[[i]][[1]]["post_bias_det95"])
    res[i,"cp_95"]<-as.numeric(p[[i]][[1]]["cp_95"])
  }
  return(res)
}

# create list of results
res.l<- list()
whichd  = "d1"
for (j in 1:63){
  iter.ind <- paste(paste(whichd, "p", sep = "_"), j, sep = "")
  iter.ls <- eval(as.symbol(iter.ind))
  print(iter.ind)
  res.l[[j]] <- get_p_results(p = iter.ls,
                              num_alphas = 11)
}

# convert to df
names(res.l) <- paste(paste(whichd, "p", sep = "_"), 1:63, sep = "") 
res.l[["d1_p3"]]
res.df <- do.call(rbind.data.frame, res.l)

# combine with holding df
d1.df <- cbind(out.df.d1, res.df)
#d1.df %>% View()
#---------------------------------#
# 1.5

d1.5_1 <- load('data/1.5_1.RData')
d1.5_2 <- load('data/1.5_2.RData')

# relabel p objects
for (i in 1:63){
  
  assign(paste("d1.5", paste("p", i, sep = ""), sep = "_"), 
         eval(as.symbol(paste("p", i, sep = ""))))
  
}



# create holding DF
out.df.d1.5 <-  data.frame(
  iter = rep(paste("p", 1:63, sep = ""), each = 11),
  b_c = 1.5,
  b_h = rep(c(rep(0, 11), rep(0.5, 11), rep(1, 11), rep(1.5, 11), 
              rep(2, 11), rep(2.5, 11), rep(3, 11)), 9),
  n_h = rep(c(rep(1, 77),rep(2, 77), rep(3, 77)), 3),
  alpha = rep(1:11, 63),
  n_strike = c(rep(6, 231), rep(10, 231), rep(15, 231))
)

get_p_results<-function(p,num_alphas)
{
  res=data.frame("post_bias"=rep(NA,num_alphas),
                 "post_mean"=rep(NA,num_alphas),
                 "post_sd"=rep(NA,num_alphas),
                 "post_bias_det80"=rep(NA,num_alphas),
                 "cp_80"=rep(NA,num_alphas),
                 "post_bias_det90"=rep(NA,num_alphas),
                 "cp_90"=rep(NA,num_alphas),
                 "post_bias_det95"=rep(NA,num_alphas),
                 "cp_95"=rep(NA,num_alphas))
  for(i in 1:11)
  {
    res[i,"post_bias"]<-as.numeric(p[[i]][[1]]["post_bias"])
    res[i,"post_mean"]<-as.numeric(p[[i]][[1]]["post_mean"])
    res[i,"post_sd"]<-as.numeric(p[[i]][[1]]["post_sd"])
    res[i,"post_bias_det80"]<-as.numeric(p[[i]][[1]]["post_bias_det80"])
    res[i,"cp_80"]<-as.numeric(p[[i]][[1]]["cp_80"])
    res[i,"post_bias_det90"]<-as.numeric(p[[i]][[1]]["post_bias_det90"])
    res[i,"cp_90"]<-as.numeric(p[[i]][[1]]["cp_90"])
    res[i,"post_bias_det95"]<-as.numeric(p[[i]][[1]]["post_bias_det95"])
    res[i,"cp_95"]<-as.numeric(p[[i]][[1]]["cp_95"])
  }
  return(res)
}

# create list of results
res.l<- list()
whichd  = "d1.5"
for (j in 1:63){
  iter.ind <- paste(paste(whichd, "p", sep = "_"), j, sep = "")
  iter.ls <- eval(as.symbol(iter.ind))
  print(iter.ind)
  res.l[[j]] <- get_p_results(p = iter.ls,
                              num_alphas = 11)
}

# convert to df
names(res.l) <- paste(paste(whichd, "p", sep = "_"), 1:63, sep = "") 
res.l[["d1.5_p3"]]
res.df <- do.call(rbind.data.frame, res.l)

# combine with holding df
d1.5.df <- cbind(out.df.d1.5, res.df)

#---------------------------------#
# 2

d2_1 <- load('data/2_1.RData')
d2_2 <- load('data/2_2.RData')

# relabel p objects
for (i in 1:63){
  
  assign(paste("d2", paste("p", i, sep = ""), sep = "_"), 
         eval(as.symbol(paste("p", i, sep = ""))))
  
}



# create holding DF
out.df.d2 <-  data.frame(
  iter = rep(paste("p", 1:63, sep = ""), each = 11),
  b_c = 2,
  b_h = rep(c(rep(0, 11), rep(0.5, 11), rep(1, 11), rep(1.5, 11), 
              rep(2, 11), rep(2.5, 11), rep(3, 11)), 9),
  n_h = rep(c(rep(1, 77),rep(2, 77), rep(3, 77)), 3),
  alpha = rep(1:11, 63),
  n_strike = c(rep(6, 231), rep(10, 231), rep(15, 231))
)

get_p_results<-function(p,num_alphas)
{
  res=data.frame("post_bias"=rep(NA,num_alphas),
                 "post_mean"=rep(NA,num_alphas),
                 "post_sd"=rep(NA,num_alphas),
                 "post_bias_det80"=rep(NA,num_alphas),
                 "cp_80"=rep(NA,num_alphas),
                 "post_bias_det90"=rep(NA,num_alphas),
                 "cp_90"=rep(NA,num_alphas),
                 "post_bias_det95"=rep(NA,num_alphas),
                 "cp_95"=rep(NA,num_alphas))
  for(i in 1:11)
  {
    res[i,"post_bias"]<-as.numeric(p[[i]][[1]]["post_bias"])
    res[i,"post_mean"]<-as.numeric(p[[i]][[1]]["post_mean"])
    res[i,"post_sd"]<-as.numeric(p[[i]][[1]]["post_sd"])
    res[i,"post_bias_det80"]<-as.numeric(p[[i]][[1]]["post_bias_det80"])
    res[i,"cp_80"]<-as.numeric(p[[i]][[1]]["cp_80"])
    res[i,"post_bias_det90"]<-as.numeric(p[[i]][[1]]["post_bias_det90"])
    res[i,"cp_90"]<-as.numeric(p[[i]][[1]]["cp_90"])
    res[i,"post_bias_det95"]<-as.numeric(p[[i]][[1]]["post_bias_det95"])
    res[i,"cp_95"]<-as.numeric(p[[i]][[1]]["cp_95"])
  }
  return(res)
}

# create list of results
res.l<- list()
whichd  = "d2"
for (j in 1:63){
  iter.ind <- paste(paste(whichd, "p", sep = "_"), j, sep = "")
  iter.ls <- eval(as.symbol(iter.ind))
  print(iter.ind)
  res.l[[j]] <- get_p_results(p = iter.ls,
                              num_alphas = 11)
}

# convert to df
names(res.l) <- paste(paste(whichd, "p", sep = "_"), 1:63, sep = "") 
res.l[["d2_p3"]]
res.df <- do.call(rbind.data.frame, res.l)

# combine with holding df
d2.df <- cbind(out.df.d2, res.df)

#---------------------------------#
# 2.5

d2.5_1 <- load('data/2.5_1.RData')
d2.5_2 <- load('data/2.5_2.RData')

# relabel p objects
for (i in 1:63){
  
  assign(paste("d2.5", paste("p", i, sep = ""), sep = "_"), 
         eval(as.symbol(paste("p", i, sep = ""))))
  
}



# create holding DF
out.df.d2.5 <-  data.frame(
  iter = rep(paste("p", 1:63, sep = ""), each = 11),
  b_c = 2.5,
  b_h = rep(c(rep(0, 11), rep(0.5, 11), rep(1, 11), rep(1.5, 11), 
              rep(2, 11), rep(2.5, 11), rep(3, 11)), 9),
  n_h = rep(c(rep(1, 77),rep(2, 77), rep(3, 77)), 3),
  alpha = rep(1:11, 63),
  n_strike = c(rep(6, 231), rep(10, 231), rep(15, 231))
)

get_p_results<-function(p,num_alphas)
{
  res=data.frame("post_bias"=rep(NA,num_alphas),
                 "post_mean"=rep(NA,num_alphas),
                 "post_sd"=rep(NA,num_alphas),
                 "post_bias_det80"=rep(NA,num_alphas),
                 "cp_80"=rep(NA,num_alphas),
                 "post_bias_det90"=rep(NA,num_alphas),
                 "cp_90"=rep(NA,num_alphas),
                 "post_bias_det95"=rep(NA,num_alphas),
                 "cp_95"=rep(NA,num_alphas))
  for(i in 1:11)
  {
    res[i,"post_bias"]<-as.numeric(p[[i]][[1]]["post_bias"])
    res[i,"post_mean"]<-as.numeric(p[[i]][[1]]["post_mean"])
    res[i,"post_sd"]<-as.numeric(p[[i]][[1]]["post_sd"])
    res[i,"post_bias_det80"]<-as.numeric(p[[i]][[1]]["post_bias_det80"])
    res[i,"cp_80"]<-as.numeric(p[[i]][[1]]["cp_80"])
    res[i,"post_bias_det90"]<-as.numeric(p[[i]][[1]]["post_bias_det90"])
    res[i,"cp_90"]<-as.numeric(p[[i]][[1]]["cp_90"])
    res[i,"post_bias_det95"]<-as.numeric(p[[i]][[1]]["post_bias_det95"])
    res[i,"cp_95"]<-as.numeric(p[[i]][[1]]["cp_95"])
  }
  return(res)
}

# create list of results
res.l<- list()
whichd  = "d2.5"
for (j in 1:63){
  iter.ind <- paste(paste(whichd, "p", sep = "_"), j, sep = "")
  iter.ls <- eval(as.symbol(iter.ind))
  print(iter.ind)
  res.l[[j]] <- get_p_results(p = iter.ls,
                              num_alphas = 11)
}

# convert to df
names(res.l) <- paste(paste(whichd, "p", sep = "_"), 1:63, sep = "") 
res.l[["d2.5_p3"]]
res.df <- do.call(rbind.data.frame, res.l)

# combine with holding df
d2.5.df <- cbind(out.df.d2.5, res.df)

#---------------------------------#
# 3

d3_1 <- load('data/3_1.RData')
d3_2 <- load('data/3_2.RData')

# relabel p objects
for (i in 1:63){
  
  assign(paste("d3", paste("p", i, sep = ""), sep = "_"), 
         eval(as.symbol(paste("p", i, sep = ""))))
  
}



# create holding DF
out.df.d3 <-  data.frame(
  iter = rep(paste("p", 1:63, sep = ""), each = 11),
  b_c = 3,
  b_h = rep(c(rep(0, 11), rep(0.5, 11), rep(1, 11), rep(1.5, 11), 
              rep(2, 11), rep(2.5, 11), rep(3, 11)), 9),
  n_h = rep(c(rep(1, 77),rep(2, 77), rep(3, 77)), 3),
  alpha = rep(1:11, 63),
  n_strike = c(rep(6, 231), rep(10, 231), rep(15, 231))
)

get_p_results<-function(p,num_alphas)
{
  res=data.frame("post_bias"=rep(NA,num_alphas),
                 "post_mean"=rep(NA,num_alphas),
                 "post_sd"=rep(NA,num_alphas),
                 "post_bias_det80"=rep(NA,num_alphas),
                 "cp_80"=rep(NA,num_alphas),
                 "post_bias_det90"=rep(NA,num_alphas),
                 "cp_90"=rep(NA,num_alphas),
                 "post_bias_det95"=rep(NA,num_alphas),
                 "cp_95"=rep(NA,num_alphas))
  for(i in 1:11)
  {
    res[i,"post_bias"]<-as.numeric(p[[i]][[1]]["post_bias"])
    res[i,"post_mean"]<-as.numeric(p[[i]][[1]]["post_mean"])
    res[i,"post_sd"]<-as.numeric(p[[i]][[1]]["post_sd"])
    res[i,"post_bias_det80"]<-as.numeric(p[[i]][[1]]["post_bias_det80"])
    res[i,"cp_80"]<-as.numeric(p[[i]][[1]]["cp_80"])
    res[i,"post_bias_det90"]<-as.numeric(p[[i]][[1]]["post_bias_det90"])
    res[i,"cp_90"]<-as.numeric(p[[i]][[1]]["cp_90"])
    res[i,"post_bias_det95"]<-as.numeric(p[[i]][[1]]["post_bias_det95"])
    res[i,"cp_95"]<-as.numeric(p[[i]][[1]]["cp_95"])
  }
  return(res)
}

# create list of results
res.l<- list()
whichd  = "d3"
for (j in 1:63){
  iter.ind <- paste(paste(whichd, "p", sep = "_"), j, sep = "")
  iter.ls <- eval(as.symbol(iter.ind))
  print(iter.ind)
  res.l[[j]] <- get_p_results(p = iter.ls,
                              num_alphas = 11)
}

# convert to df
names(res.l) <- paste(paste(whichd, "p", sep = "_"), 1:63, sep = "") 
res.l[["d3_p3"]]
res.df <- do.call(rbind.data.frame, res.l)

# combine with holding df
d3.df <- cbind(out.df.d3, res.df)


comb.df <- rbind(d0.df, d0.5.df, d1.df, d1.5.df, 
                 d2.df, d2.5.df, d3.df)




comb.df$alpha.val <- rep(seq(from= 0, to  = 1, by = 0.1), 441)

head(comb.df)
colnames(comb.df)

write.csv(comb.df, "data/simulation_data_all.csv", row.names = FALSE)

#--------------------------------------------------------------#
#--------------------------------------------------------------#

# Plotting 

library(ggplot2)
library(viridis)
library(cowplot)
library(RColorBrewer)

df.eq <- data.frame(b_h = seq(from = 0, to = 3, by = 0.5), 
                    b_c = seq(from = 0, to = 3, by = 0.5))


# New facet label names for dose variable
hist.labs <- c("N. Historical = 1", "N. Historical = 2", "N. Historical = 3")
names(hist.labs) <- c("1", "2", "3")

# New facet label names for supp variable
alpha.labs <- c("alpha = 0.1", 
                "alpha = 0.5",
                "alpha = 1")
names(alpha.labs) <- c("0.1", "0.5", "1")

pp_15 <- 
  comb.df %>%
  filter(n_strike==15, alpha.val %in% c(0.1, 0.5, 1)) %>%
  ggplot(data = ., aes(x = b_h, y = b_c, fill = post_bias_det90), 
         color="black")+
  geom_tile(color = "black", alpha = 0.9)+
  geom_rect(data = df.eq, aes (xmin = -0.25, xmax = 0.25, 
                               ymin = -0.25, ymax = 0.25),
            color = "black", lwd = 1.2,
            fill = "transparent")+
  coord_equal()+
  geom_text(aes(label = round(post_bias_det80, 2), color = post_bias_det80), 
            size = 2.3, fontface = "bold")+
  scale_color_gradient2(low = "grey35",mid = "grey55", 
                        high = "white", guide = "none")+
  scale_fill_viridis("Bias Detection Rate",direction=-1,
                     option = "inferno", limits = c(0, 1))+
  scale_x_continuous(breaks = c(0:3), expand = c(0,0))+
  scale_y_continuous(breaks = c(0:3), expand = c(0,0))+
  facet_grid(n_h~alpha.val, labeller = labeller(n_h = hist.labs, 
                                                alpha.val = alpha.labs))+
  theme_classic()+
  xlab("Historical Bias")+
  ylab("Current Bias")+
  ggtitle("N Strike = 15")+
  theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        legend.position = "bottom")




pp_10 <- 
  comb.df %>%
  filter(n_strike==10, alpha.val %in% c(0.1, 0.5, 1)) %>%
  ggplot(data = ., aes(x = b_h, y = b_c, fill = post_bias_det80), 
         color="black")+
  geom_tile(color = "black", alpha = 0.9)+
  geom_rect(data = df.eq, aes (xmin = -0.25, xmax = 0.25, 
                               ymin = -0.25, ymax = 0.25),
            color = "black", lwd = 1.2,
            fill = "transparent")+
  coord_equal()+
  geom_text(aes(label = round(post_bias_det80, 2), color = post_bias_det80), 
            size = 2.3, fontface = "bold")+
  scale_color_gradient2(low = "grey35",mid = "grey55", 
                        high = "white", guide = "none")+
  scale_fill_viridis("Bias Detection Rate",direction=-1,
                     option = "inferno", limits = c(0, 1))+
  scale_x_continuous(breaks = c(0:3), expand = c(0,0))+
  scale_y_continuous(breaks = c(0:3), expand = c(0,0))+
  facet_grid(n_h~alpha.val, labeller = labeller(n_h = hist.labs, 
                                                alpha.val = alpha.labs))+
  theme_classic()+
  xlab("Historical Bias")+
  ylab("Current Bias")+
  ggtitle("N Strike = 10")+
  theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        legend.position = "bottom")


pp_6 <- 
  comb.df %>%
  filter(n_strike==6, alpha.val %in% c(0.1, 0.5, 1)) %>%
  ggplot(data = ., aes(x = b_h, y = b_c, fill = post_bias_det80), 
         color="black")+
  geom_tile(color = "black", alpha = 0.9)+
  geom_rect(data = df.eq, aes (xmin = -0.25, xmax = 0.25, 
                               ymin = -0.25, ymax = 0.25),
            color = "black", lwd = 1.2,
            fill = "transparent")+
  coord_equal()+
  geom_text(aes(label = round(post_bias_det80, 2), color = post_bias_det80), 
            size = 2.3, fontface = "bold")+
  scale_color_gradient2(low = "grey35",mid = "grey55", 
                        high = "white", guide = "none")+
  scale_fill_viridis("Bias Detection Rate",direction=-1,
                     option = "inferno", limits = c(0, 1))+
  scale_x_continuous(breaks = c(0:3), expand = c(0,0))+
  scale_y_continuous(breaks = c(0:3), expand = c(0,0))+
  facet_grid(n_h~alpha.val, labeller = labeller(n_h = hist.labs, 
                                                alpha.val = alpha.labs))+
  theme_classic()+
  xlab("Historical Bias")+
  ylab("Current Bias")+
  ggtitle("N Strike = 6")+
  theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        legend.position = "bottom", 
        legend.title.align = -0.5)


ggsave(plot = pp_15, filename = "pp15_80CI.png", height = 8, width = 8,
       units = "in", dpi = 300)

ggsave(plot = pp_10, filename = "pp10_80CI.png", height = 8, width = 8,
       units = "in", dpi = 300)

ggsave(plot = pp_6, filename = "pp6_80CI.png", height = 8, width = 8,
       units = "in", dpi = 300)



#------------------------------------------------------------------------------#

# Compatibility plots

n_6_comp <- comb.df %>%
  filter(n_strike==6, alpha.val %in% c(0.1, 0.5, 1), 
         b_h == 0 & b_c== 0 | b_h == 0.5 & b_c== 0.5 |
           b_h == 1 & b_c== 1| b_h == 1.5 & b_c== 1.5|
           b_h == 2 & b_c== 2| b_h == 2.5 & b_c== 2.5|
           b_h == 3 & b_c== 3)

n_10_comp <- comb.df %>%
  filter(n_strike==10, alpha.val %in% c(0.1, 0.5, 1), 
         b_h == 0 & b_c== 0 | b_h == 0.5 & b_c== 0.5 |
           b_h == 1 & b_c== 1| b_h == 1.5 & b_c== 1.5|
           b_h == 2 & b_c== 2| b_h == 2.5 & b_c== 2.5|
           b_h == 3 & b_c== 3)

n_15_comp <- comb.df %>%
  filter(n_strike==15, alpha.val %in% c(0.1, 0.5, 1), 
         b_h == 0 & b_c== 0 | b_h == 0.5 & b_c== 0.5 |
           b_h == 1 & b_c== 1| b_h == 1.5 & b_c== 1.5|
           b_h == 2 & b_c== 2| b_h == 2.5 & b_c== 2.5|
           b_h == 3 & b_c== 3)

comp6 <-
  n_6_comp %>%
  ggplot(data = ., aes(y = post_bias_det95, x = b_h, color = as.factor(alpha.val)))+
  geom_point(size = 3, alpha = 0.6) +
  geom_line(lwd = 1.05, alpha = 0.6) +
  geom_hline(yintercept = 0.5)+
  
  facet_grid(~n_h) +
  theme_classic()+
  xlab("Bias")+
  ylab("Bias Detection Rate")+
  scale_color_manual("Alpha", values = c("grey88", "grey66", "grey10"))+
  theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        legend.position = "bottom", 
        legend.title.align = -0.5)

comp10 <-
  n_10_comp %>%
  ggplot(data = ., aes(y = post_bias_det95, x = b_h, color = as.factor(alpha.val)))+
  geom_point(size = 3, alpha = 0.6) +
  geom_line(lwd = 1.05, alpha = 0.6) +
  geom_hline(yintercept = 0.5)+
  
  facet_grid(~n_h) +
  theme_classic()+
  xlab("Bias")+
  ylab("Bias Detection Rate")+
  scale_color_manual("Alpha", values = c("grey88", "grey66", "grey10"))+
  theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        legend.position = "bottom", 
        legend.title.align = -0.5)

comp15 <-
  n_15_comp %>%
  ggplot(data = ., aes(y = post_bias_det95, x = b_h, color = as.factor(alpha.val)))+
  geom_point(size = 3, alpha = 0.6) +
  geom_line(lwd = 1.05, alpha = 0.6) +
  geom_hline(yintercept = 0.5)+
  facet_grid(~n_h) +
  theme_classic()+
  xlab("Bias")+
  ylab("Bias Detection Rate")+
  scale_color_manual("Alpha", values = c("grey88", "grey66", "grey10"))+
  theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        legend.position = "bottom", 
        legend.title.align = -0.5, 
        strip.background = element_rect(fill="grey95"))

cowplot::plot_grid(comp6, comp10,
                   comp15, ncol = 1)


comp_comb <-comb.df %>%
  filter(n_strike %in% c(6, 10,  15), n_h %in% c(1, 3), alpha.val %in% c(0.1, 0.5, 1), 
         b_h == 0 & b_c== 0 | b_h == 0.5 & b_c== 0.5 |
           b_h == 1 & b_c== 1| b_h == 1.5 & b_c== 1.5|
           b_h == 2 & b_c== 2| b_h == 2.5 & b_c== 2.5|
           b_h == 3 & b_c== 3)


comp_comb <- comp_comb %>% mutate(n_strike_lab = 
                                    case_when(n_strike ==6 ~ "N. strikes = 6",
                                              n_strike ==10 ~ "N. strikes = 10",
                                              n_strike ==15 ~ "N. strikes = 15"))
comp_comb$n_strike_lab <- factor(comp_comb$n_strike_lab, levels = c("N. strikes = 6",
                                                                    "N. strikes = 10",
                                                                    "N. strikes = 15"), 
                                 ordered = TRUE) 

comp_comb %>% mutate(n_h = as.factor(n_h)) %>% 
  ggplot(data = ., aes(y = post_bias_det95, x = b_h, group = as.factor(alpha.val)))+
  geom_line(lwd = 1.01, alpha = 1) +
  geom_point(size = 3, alpha = 1, aes(pch= as.factor(alpha.val))) +
  facet_grid(vars(n_h), vars(n_strike_lab)) +
  #scale_linetype_manual("Number of Historical Trials", values = c(1, 1, 1))+
  scale_shape_manual("Value of alpha", values = c(0, 1, 2))+
  theme_half_open()+
  #geom_hline(yintercept = 0)+
  xlab("Bias")+
  #scale_y_continuous(expand = c(0, 0))+
  ylab("Bias Detection Rate")+
  scale_color_manual("Alpha", values = c("orange", "purple", "black"))+
  theme(axis.text = element_text(size = 11), 
        axis.title = element_text(size = 14), 
        legend.position = "bottom", 
        #legend.title.align = -0.5, 
        axis.line = element_line(), 
        panel.grid.major = element_line(color = "grey88"), 
        panel.grid.minor = element_line(color = "grey88"), 
        strip.background = element_rect(fill="grey95"))
ggsave(filename = "compatibility_plot_23.jpg", height = 8, width = 10, 
       units = "in", dpi = 300, bg = "white")

#------------------------------------------------------------------------------#

# CHECK OF SENTIVITY TO SD OF INITIAL PRIOR

sd0 <- load('data/sd_sensitivity/sd_sens_0.RData')
sd1 <- load('data/sd_sensitivity/sd_sens_1.RData')
sd2 <- load('data/sd_sensitivity/sd_sens_2.RData')
#-----------------------------------------#

sd_df <-  data.frame(
  b_c = rep(c(0, 1, 2), each = 12),
  b_h = rep(c(0, 1, 2), each = 12),
  alpha = rep(c(0.1, 0.5, 1), ),
  prior_sd  = rep(rep(c(1, 100, 1, 2), each = 3), 3), 
  prior_mean  = rep(rep(c(0, 0, 1, 1), each = 3), 3), 
  post_bias_det95 = NA
)

## b=0
# N(0, 1)
sd_df$post_bias_det95[1] <- p_0_1[[1]][[1]][[8]]
sd_df$post_bias_det95[2] <- p_0_1[[2]][[1]][[8]]
sd_df$post_bias_det95[3] <- p_0_1[[3]][[1]][[8]]
# N(0, 100)
sd_df$post_bias_det95[4] <- p_0_2[[1]][[1]][[8]]
sd_df$post_bias_det95[5] <- p_0_2[[2]][[1]][[8]]
sd_df$post_bias_det95[6] <- p_0_2[[3]][[1]][[8]]
# N(1, 1)
sd_df$post_bias_det95[7] <- p_0_3[[1]][[1]][[8]]
sd_df$post_bias_det95[8] <- p_0_3[[2]][[1]][[8]]
sd_df$post_bias_det95[9] <- p_0_3[[3]][[1]][[8]]
# N(1, 2)
sd_df$post_bias_det95[10] <- p_0_4[[1]][[1]][[8]]
sd_df$post_bias_det95[11] <- p_0_4[[2]][[1]][[8]]
sd_df$post_bias_det95[12] <- p_0_4[[3]][[1]][[8]]

## b=1
# N(0, 1)
sd_df$post_bias_det95[13] <- p_1_1[[1]][[1]][[8]]
sd_df$post_bias_det95[14] <- p_1_1[[2]][[1]][[8]]
sd_df$post_bias_det95[15] <- p_1_1[[3]][[1]][[8]]
# N(0, 100)
sd_df$post_bias_det95[16] <- p_1_2[[1]][[1]][[8]]
sd_df$post_bias_det95[17] <- p_1_2[[2]][[1]][[8]]
sd_df$post_bias_det95[18] <- p_1_2[[3]][[1]][[8]]
# N(1, 1)
sd_df$post_bias_det95[19] <- p_1_3[[1]][[1]][[8]]
sd_df$post_bias_det95[20] <- p_1_3[[2]][[1]][[8]]
sd_df$post_bias_det95[21] <- p_1_3[[3]][[1]][[8]]
# N(1, 2)
sd_df$post_bias_det95[22] <- p_1_4[[1]][[1]][[8]]
sd_df$post_bias_det95[23] <- p_1_4[[2]][[1]][[8]]
sd_df$post_bias_det95[24] <- p_1_4[[3]][[1]][[8]]

## b=2
# N(0, 1)
sd_df$post_bias_det95[25] <- p_2_1[[1]][[1]][[8]]
sd_df$post_bias_det95[26] <- p_2_1[[2]][[1]][[8]]
sd_df$post_bias_det95[27] <- p_2_1[[3]][[1]][[8]]
# N(0, 100)
sd_df$post_bias_det95[28] <- p_2_2[[1]][[1]][[8]]
sd_df$post_bias_det95[29] <- p_2_2[[2]][[1]][[8]]
sd_df$post_bias_det95[30] <- p_2_2[[3]][[1]][[8]]
# N(1, 1)
sd_df$post_bias_det95[31] <- p_2_3[[1]][[1]][[8]]
sd_df$post_bias_det95[32] <- p_2_3[[2]][[1]][[8]]
sd_df$post_bias_det95[33] <- p_2_3[[3]][[1]][[8]]
# N(1, 2)
sd_df$post_bias_det95[34] <- p_2_4[[1]][[1]][[8]]
sd_df$post_bias_det95[35] <- p_2_4[[2]][[1]][[8]]
sd_df$post_bias_det95[36] <- p_2_4[[3]][[1]][[8]]


sd_df_0 <- sd_df %>% filter(prior_mean==0)
sd_df_0  


# get data for n(0, 2) case (in the main paper)
comp_comb_2 <- comp_comb %>% filter(b_c %in% c(0, 1, 2),
                                    n_strike %in% c(10), n_h ==3) %>% 
  dplyr::select(b_c, b_h, alpha.val, post_bias_det95 )

comp_comb_2$prior_sd <- 2
comp_comb_2$prior_mean <- 0

comp_comb_2 <- comp_comb_2 %>% dplyr::select(b_c, b_h, alpha.val,prior_sd, 
                                             prior_mean, post_bias_det95)
names(comp_comb_2)[3]<-"alpha"
sd_df_comb <- rbind(sd_df_0, comp_comb_2)

sd_df_comb$alpha <- as.factor(sd_df_comb$alpha)
sd_df_comb$prior_sd <- as.factor(sd_df_comb$prior_sd)

ggplot(data = sd_df_comb , aes(x = b_h, y = post_bias_det95, 
                               lty = prior_sd, color = prior_sd))+
  geom_line(alpha = 0.9, lwd = 1.05)+
  geom_point(size = 3)+
  scale_linetype_manual("SD of Initial Prior", 
                        values = c(1, 2, 3))+
  scale_color_manual("SD of Initial Prior", 
                     values = rev(c("grey0", "grey35", "grey75")))+
  facet_grid(~alpha)+
  theme_half_open()+
  xlab("Bias")+
  ylab("Bias Detection Rate")+
  theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        panel.grid.major = element_line(color = "grey92"), 
        panel.grid.minor = element_line(color = "grey92"),
        legend.position = "bottom", 
        legend.key.size = unit(3, 'cm'))
ggsave(filename = "SD_sensitivity_23.jpg",
       height = 6, width = 8, bg = "white",
       units = "in", dpi = 300)

#-----------------------------------------#

sd_df <-  data.frame(
  b_c = rep(c(0, 1, 2), each = 12),
  b_h = rep(c(0, 1, 2), each = 12),
  alpha = rep(c(0.1, 0.5, 1), ),
  prior_sd  = rep(rep(c(1, 100, 1, 2), each = 3), 3), 
  prior_mean  = rep(rep(c(0, 0, 1, 1), each = 3), 3), 
  post_sd = NA
)

## b=0
# N(0, 1)
sd_df$post_sd[1] <- p_0_1[[1]][[1]][[2]]
sd_df$post_sd[2] <- p_0_1[[2]][[1]][[2]]
sd_df$post_sd[3] <- p_0_1[[3]][[1]][[2]]
# N(0, 100)
sd_df$post_sd[4] <- p_0_2[[1]][[1]][[2]]
sd_df$post_sd[5] <- p_0_2[[2]][[1]][[2]]
sd_df$post_sd[6] <- p_0_2[[3]][[1]][[2]]
# N(1, 1)
sd_df$post_sd[7] <- p_0_3[[1]][[1]][[2]]
sd_df$post_sd[8] <- p_0_3[[2]][[1]][[2]]
sd_df$post_sd[9] <- p_0_3[[3]][[1]][[2]]
# N(1, 2)
sd_df$post_sd[10] <- p_0_4[[1]][[1]][[2]]
sd_df$post_sd[11] <- p_0_4[[2]][[1]][[2]]
sd_df$post_sd[12] <- p_0_4[[3]][[1]][[2]]

## b=1
# N(0, 1)
sd_df$post_sd[13] <- p_1_1[[1]][[1]][[2]]
sd_df$post_sd[14] <- p_1_1[[2]][[1]][[2]]
sd_df$post_sd[15] <- p_1_1[[3]][[1]][[2]]
# N(0, 100)
sd_df$post_sd[16] <- p_1_2[[1]][[1]][[2]]
sd_df$post_sd[17] <- p_1_2[[2]][[1]][[2]]
sd_df$post_sd[18] <- p_1_2[[3]][[1]][[2]]
# N(1, 1)
sd_df$post_sd[19] <- p_1_3[[1]][[1]][[2]]
sd_df$post_sd[20] <- p_1_3[[2]][[1]][[2]]
sd_df$post_sd[21] <- p_1_3[[3]][[1]][[2]]
# N(1, 2)
sd_df$post_sd[22] <- p_1_4[[1]][[1]][[2]]
sd_df$post_sd[23] <- p_1_4[[2]][[1]][[2]]
sd_df$post_sd[24] <- p_1_4[[3]][[1]][[2]]

## b=2
# N(0, 1)
sd_df$post_sd[25] <- p_2_1[[1]][[1]][[2]]
sd_df$post_sd[26] <- p_2_1[[2]][[1]][[2]]
sd_df$post_sd[27] <- p_2_1[[3]][[1]][[2]]
# N(0, 100)
sd_df$post_sd[28] <- p_2_2[[1]][[1]][[2]]
sd_df$post_sd[29] <- p_2_2[[2]][[1]][[2]]
sd_df$post_sd[30] <- p_2_2[[3]][[1]][[2]]
# N(1, 1)
sd_df$post_sd[31] <- p_2_3[[1]][[1]][[2]]
sd_df$post_sd[32] <- p_2_3[[2]][[1]][[2]]
sd_df$post_sd[33] <- p_2_3[[3]][[1]][[2]]
# N(1, 2)
sd_df$post_sd[34] <- p_2_4[[1]][[1]][[2]]
sd_df$post_sd[35] <- p_2_4[[2]][[1]][[2]]
sd_df$post_sd[36] <- p_2_4[[3]][[1]][[2]]


sd_df$alpha <- as.factor(sd_df$alpha)
sd_df$prior_sd <- as.factor(sd_df$prior_sd)
sd_df %>% filter(prior_mean==0) %>%
  ggplot(data = ., aes(x = b_h, y = post_sd, 
                       color=alpha, lty = prior_sd))+
  geom_line(alpha = 0.9, lwd = 1.05)+
  geom_abline(intercept = 0, slope = 1)+
  geom_point(size = 3)+
  xlab("Bias")+
  ylab("Post Mean")+
  theme_classic()+
  theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        legend.position = "bottom", 
        legend.title.align = -0.5)


#-----------------------------------------#

sd_df <-  data.frame(
  b_c = rep(c(0, 1, 2), each = 12),
  b_h = rep(c(0, 1, 2), each = 12),
  alpha = rep(c(0.1, 0.5, 1), ),
  prior_sd  = rep(rep(c(1, 100, 1, 2), each = 3), 3), 
  prior_mean  = rep(rep(c(0, 0, 1, 1), each = 3), 3), 
  post_sd = NA
)

## b=0
# N(0, 1)
sd_df$post_sd[1] <- p_0_1[[1]][[1]][[1]]
sd_df$post_sd[2] <- p_0_1[[2]][[1]][[1]]
sd_df$post_sd[3] <- p_0_1[[3]][[1]][[1]]
# N(0, 100)
sd_df$post_sd[4] <- p_0_2[[1]][[1]][[1]]
sd_df$post_sd[5] <- p_0_2[[2]][[1]][[1]]
sd_df$post_sd[6] <- p_0_2[[3]][[1]][[1]]
# N(1, 1)
sd_df$post_sd[7] <- p_0_3[[1]][[1]][[1]]
sd_df$post_sd[8] <- p_0_3[[2]][[1]][[1]]
sd_df$post_sd[9] <- p_0_3[[3]][[1]][[1]]
# N(1, 2)
sd_df$post_sd[10] <- p_0_4[[1]][[1]][[1]]
sd_df$post_sd[11] <- p_0_4[[2]][[1]][[1]]
sd_df$post_sd[12] <- p_0_4[[3]][[1]][[1]]

## b=1
# N(0, 1)
sd_df$post_sd[13] <- p_1_1[[1]][[1]][[1]]
sd_df$post_sd[14] <- p_1_1[[2]][[1]][[1]]
sd_df$post_sd[15] <- p_1_1[[3]][[1]][[1]]
# N(0, 100)
sd_df$post_sd[16] <- p_1_2[[1]][[1]][[1]]
sd_df$post_sd[17] <- p_1_2[[2]][[1]][[1]]
sd_df$post_sd[18] <- p_1_2[[3]][[1]][[1]]
# N(1, 1)
sd_df$post_sd[19] <- p_1_3[[1]][[1]][[1]]
sd_df$post_sd[20] <- p_1_3[[2]][[1]][[1]]
sd_df$post_sd[21] <- p_1_3[[3]][[1]][[1]]
# N(1, 2)
sd_df$post_sd[22] <- p_1_4[[1]][[1]][[1]]
sd_df$post_sd[23] <- p_1_4[[2]][[1]][[1]]
sd_df$post_sd[24] <- p_1_4[[3]][[1]][[1]]

## b=2
# N(0, 1)
sd_df$post_sd[25] <- p_2_1[[1]][[1]][[1]]
sd_df$post_sd[26] <- p_2_1[[2]][[1]][[1]]
sd_df$post_sd[27] <- p_2_1[[3]][[1]][[1]]
# N(0, 100)
sd_df$post_sd[28] <- p_2_2[[1]][[1]][[1]]
sd_df$post_sd[29] <- p_2_2[[2]][[1]][[1]]
sd_df$post_sd[30] <- p_2_2[[3]][[1]][[1]]
# N(1, 1)
sd_df$post_sd[31] <- p_2_3[[1]][[1]][[1]]
sd_df$post_sd[32] <- p_2_3[[2]][[1]][[1]]
sd_df$post_sd[33] <- p_2_3[[3]][[1]][[1]]
# N(1, 2)
sd_df$post_sd[34] <- p_2_4[[1]][[1]][[1]]
sd_df$post_sd[35] <- p_2_4[[2]][[1]][[1]]
sd_df$post_sd[36] <- p_2_4[[3]][[1]][[1]]


sd_df$alpha <- as.factor(sd_df$alpha)
sd_df$prior_sd <- as.factor(sd_df$prior_sd)
sd_df %>% filter(prior_mean==0) %>%
  ggplot(data = ., aes(x = b_h, y = post_sd, 
                       color=alpha, lty = prior_sd))+
  geom_line(alpha = 0.9, lwd = 1.05)+
  #geom_abline(intercept = 0, slope = 1)+
  geom_point(size = 3)+
  xlab("Bias")+
  ylab("Post Bias")+
  theme_classic()+
  theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        legend.position = "bottom", 
        legend.title.align = -0.5)
