# New simulations - March 2022
library(dplyr)
library(tidyr)
library(stringr)

# STEPS

##STEP1 -  load and reformat output generated by 'model.R' code
##STEP2 -  combine all into data frame for plotting
##STEP3 - plot in ggplot2


d0_1 <- load('data/01.RData')
d0_2 <- load('data/02.RData')

#i=1
for (i in 1:63){

  assign(paste("d0", paste("p", i, sep = ""), sep = "_"),
         eval(as.symbol(paste("p", i, sep = ""))))

}



# create holding DF
out.df.d0 <-  data.frame(
  iter = rep(paste("p", 1:63, sep = ""), each = 11),
  b_c = 0,
  b_h = rep(c(rep(0, 11), rep(0.5, 11), rep(1, 11), rep(1.5, 11),
              rep(2, 11), rep(2.5, 11), rep(3, 11)), 9),
  n_h = rep(c(rep(1, 77),rep(2, 77), rep(3, 77)), 3),
  alpha = rep(1:11, 63),
  n_strike = c(rep(6, 231), rep(10, 231), rep(15, 231))
)

get_p_results<-function(p,num_alphas)
{
  res=data.frame("post_bias"=rep(NA,num_alphas),
                 "post_mean"=rep(NA,num_alphas),
                 "post_sd"=rep(NA,num_alphas),
                 "post_bias_det80"=rep(NA,num_alphas),
                 "cp_80"=rep(NA,num_alphas),
                 "post_bias_det90"=rep(NA,num_alphas),
                 "cp_90"=rep(NA,num_alphas),
                 "post_bias_det95"=rep(NA,num_alphas),
                 "cp_95"=rep(NA,num_alphas))
  for(i in 1:11)
  {
    res[i,"post_bias"]<-as.numeric(p[[i]][[1]]["post_bias"])
    res[i,"post_mean"]<-as.numeric(p[[i]][[1]]["post_mean"])
    res[i,"post_sd"]<-as.numeric(p[[i]][[1]]["post_sd"])
    res[i,"post_bias_det80"]<-as.numeric(p[[i]][[1]]["post_bias_det80"])
    res[i,"cp_80"]<-as.numeric(p[[i]][[1]]["cp_80"])
    res[i,"post_bias_det90"]<-as.numeric(p[[i]][[1]]["post_bias_det90"])
    res[i,"cp_90"]<-as.numeric(p[[i]][[1]]["cp_90"])
    res[i,"post_bias_det95"]<-as.numeric(p[[i]][[1]]["post_bias_det95"])
    res[i,"cp_95"]<-as.numeric(p[[i]][[1]]["cp_95"])
  }
  return(res)
}

# create list of results
whichd="d0"
res.l<- list()
for (j in 1:63){
  iter.ind <- paste(paste(whichd, "p", sep = "_"), j, sep = "")
  iter.ls <- eval(as.symbol(iter.ind))
  print(iter.ind)
  res.l[[j]] <- get_p_results(p = iter.ls,
                              num_alphas = 11)
}

# convert to df
names(res.l) <- paste(paste(whichd, "p", sep = "_"), 1:63, sep = "")
res.l[["d0_p3"]]
res.df <- do.call(rbind.data.frame, res.l)

# combine with holding df
d0.df <- cbind(out.df.d0, res.df)


#---------------------------------#
# 0.5


d0.5_1 <- load('data/_.5_1.RData')
d0.5_2 <- load('data/_.5_2.RData')

# relabel p objects
for (i in 1:63){
  
  assign(paste("d0.5", paste("p", i, sep = ""), sep = "_"), 
         eval(as.symbol(paste("p", i, sep = ""))))
  
}



# create holding DF
out.df.d0.5 <-  data.frame(
  iter = rep(paste("p", 1:63, sep = ""), each = 11),
  b_c = 0.5,
  b_h = rep(c(rep(0, 11), rep(0.5, 11), rep(1, 11), rep(1.5, 11), 
              rep(2, 11), rep(2.5, 11), rep(3, 11)), 9),
  n_h = rep(c(rep(1, 77),rep(2, 77), rep(3, 77)), 3),
  alpha = rep(1:11, 63),
  n_strike = c(rep(6, 231), rep(10, 231), rep(15, 231))
)

get_p_results<-function(p,num_alphas)
{
  res=data.frame("post_bias"=rep(NA,num_alphas),
                 "post_mean"=rep(NA,num_alphas),
                 "post_sd"=rep(NA,num_alphas),
                 "post_bias_det80"=rep(NA,num_alphas),
                 "cp_80"=rep(NA,num_alphas),
                 "post_bias_det90"=rep(NA,num_alphas),
                 "cp_90"=rep(NA,num_alphas),
                 "post_bias_det95"=rep(NA,num_alphas),
                 "cp_95"=rep(NA,num_alphas))
  for(i in 1:11)
  {
    res[i,"post_bias"]<-as.numeric(p[[i]][[1]]["post_bias"])
    res[i,"post_mean"]<-as.numeric(p[[i]][[1]]["post_mean"])
    res[i,"post_sd"]<-as.numeric(p[[i]][[1]]["post_sd"])
    res[i,"post_bias_det80"]<-as.numeric(p[[i]][[1]]["post_bias_det80"])
    res[i,"cp_80"]<-as.numeric(p[[i]][[1]]["cp_80"])
    res[i,"post_bias_det90"]<-as.numeric(p[[i]][[1]]["post_bias_det90"])
    res[i,"cp_90"]<-as.numeric(p[[i]][[1]]["cp_90"])
    res[i,"post_bias_det95"]<-as.numeric(p[[i]][[1]]["post_bias_det95"])
    res[i,"cp_95"]<-as.numeric(p[[i]][[1]]["cp_95"])
  }
  return(res)
}

# create list of results
res.l<- list()
whichd  = "d0.5"
for (j in 1:63){
  iter.ind <- paste(paste(whichd, "p", sep = "_"), j, sep = "")
  iter.ls <- eval(as.symbol(iter.ind))
  print(iter.ind)
  res.l[[j]] <- get_p_results(p = iter.ls,
                              num_alphas = 11)
}

# convert to df
names(res.l) <- paste(paste(whichd, "p", sep = "_"), 1:63, sep = "") 
res.l[["d0.5_p3"]]
res.df <- do.call(rbind.data.frame, res.l)

# combine with holding df
d0.5.df <- cbind(out.df.d0.5, res.df)
#d0.5.df %>% View()

#---------------------------------#
# 1


d1_1 <- load('data/1_1.RData')
d1_2 <- load('data/1_2.RData')

# relabel p objects
for (i in 1:63){
  
  assign(paste("d1", paste("p", i, sep = ""), sep = "_"), 
         eval(as.symbol(paste("p", i, sep = ""))))
  
}



# create holding DF
out.df.d1 <-  data.frame(
  iter = rep(paste("p", 1:63, sep = ""), each = 11),
  b_c = 1,
  b_h = rep(c(rep(0, 11), rep(0.5, 11), rep(1, 11), rep(1.5, 11), 
              rep(2, 11), rep(2.5, 11), rep(3, 11)), 9),
  n_h = rep(c(rep(1, 77),rep(2, 77), rep(3, 77)), 3),
  alpha = rep(1:11, 63),
  n_strike = c(rep(6, 231), rep(10, 231), rep(15, 231))
)

get_p_results<-function(p,num_alphas)
{
  res=data.frame("post_bias"=rep(NA,num_alphas),
                 "post_mean"=rep(NA,num_alphas),
                 "post_sd"=rep(NA,num_alphas),
                 "post_bias_det80"=rep(NA,num_alphas),
                 "cp_80"=rep(NA,num_alphas),
                 "post_bias_det90"=rep(NA,num_alphas),
                 "cp_90"=rep(NA,num_alphas),
                 "post_bias_det95"=rep(NA,num_alphas),
                 "cp_95"=rep(NA,num_alphas))
  for(i in 1:11)
  {
    res[i,"post_bias"]<-as.numeric(p[[i]][[1]]["post_bias"])
    res[i,"post_mean"]<-as.numeric(p[[i]][[1]]["post_mean"])
    res[i,"post_sd"]<-as.numeric(p[[i]][[1]]["post_sd"])
    res[i,"post_bias_det80"]<-as.numeric(p[[i]][[1]]["post_bias_det80"])
    res[i,"cp_80"]<-as.numeric(p[[i]][[1]]["cp_80"])
    res[i,"post_bias_det90"]<-as.numeric(p[[i]][[1]]["post_bias_det90"])
    res[i,"cp_90"]<-as.numeric(p[[i]][[1]]["cp_90"])
    res[i,"post_bias_det95"]<-as.numeric(p[[i]][[1]]["post_bias_det95"])
    res[i,"cp_95"]<-as.numeric(p[[i]][[1]]["cp_95"])
  }
  return(res)
}

# create list of results
res.l<- list()
whichd  = "d1"
for (j in 1:63){
  iter.ind <- paste(paste(whichd, "p", sep = "_"), j, sep = "")
  iter.ls <- eval(as.symbol(iter.ind))
  print(iter.ind)
  res.l[[j]] <- get_p_results(p = iter.ls,
                              num_alphas = 11)
}

# convert to df
names(res.l) <- paste(paste(whichd, "p", sep = "_"), 1:63, sep = "") 
res.l[["d1_p3"]]
res.df <- do.call(rbind.data.frame, res.l)

# combine with holding df
d1.df <- cbind(out.df.d1, res.df)
#d1.df %>% View()
#---------------------------------#
# 1.5

d1.5_1 <- load('data/1.5_1.RData')
d1.5_2 <- load('data/1.5_2.RData')

# relabel p objects
for (i in 1:63){
  
  assign(paste("d1.5", paste("p", i, sep = ""), sep = "_"), 
         eval(as.symbol(paste("p", i, sep = ""))))
  
}



# create holding DF
out.df.d1.5 <-  data.frame(
  iter = rep(paste("p", 1:63, sep = ""), each = 11),
  b_c = 1.5,
  b_h = rep(c(rep(0, 11), rep(0.5, 11), rep(1, 11), rep(1.5, 11), 
              rep(2, 11), rep(2.5, 11), rep(3, 11)), 9),
  n_h = rep(c(rep(1, 77),rep(2, 77), rep(3, 77)), 3),
  alpha = rep(1:11, 63),
  n_strike = c(rep(6, 231), rep(10, 231), rep(15, 231))
)

get_p_results<-function(p,num_alphas)
{
  res=data.frame("post_bias"=rep(NA,num_alphas),
                 "post_mean"=rep(NA,num_alphas),
                 "post_sd"=rep(NA,num_alphas),
                 "post_bias_det80"=rep(NA,num_alphas),
                 "cp_80"=rep(NA,num_alphas),
                 "post_bias_det90"=rep(NA,num_alphas),
                 "cp_90"=rep(NA,num_alphas),
                 "post_bias_det95"=rep(NA,num_alphas),
                 "cp_95"=rep(NA,num_alphas))
  for(i in 1:11)
  {
    res[i,"post_bias"]<-as.numeric(p[[i]][[1]]["post_bias"])
    res[i,"post_mean"]<-as.numeric(p[[i]][[1]]["post_mean"])
    res[i,"post_sd"]<-as.numeric(p[[i]][[1]]["post_sd"])
    res[i,"post_bias_det80"]<-as.numeric(p[[i]][[1]]["post_bias_det80"])
    res[i,"cp_80"]<-as.numeric(p[[i]][[1]]["cp_80"])
    res[i,"post_bias_det90"]<-as.numeric(p[[i]][[1]]["post_bias_det90"])
    res[i,"cp_90"]<-as.numeric(p[[i]][[1]]["cp_90"])
    res[i,"post_bias_det95"]<-as.numeric(p[[i]][[1]]["post_bias_det95"])
    res[i,"cp_95"]<-as.numeric(p[[i]][[1]]["cp_95"])
  }
  return(res)
}

# create list of results
res.l<- list()
whichd  = "d1.5"
for (j in 1:63){
  iter.ind <- paste(paste(whichd, "p", sep = "_"), j, sep = "")
  iter.ls <- eval(as.symbol(iter.ind))
  print(iter.ind)
  res.l[[j]] <- get_p_results(p = iter.ls,
                              num_alphas = 11)
}

# convert to df
names(res.l) <- paste(paste(whichd, "p", sep = "_"), 1:63, sep = "") 
res.l[["d1.5_p3"]]
res.df <- do.call(rbind.data.frame, res.l)

# combine with holding df
d1.5.df <- cbind(out.df.d1.5, res.df)

#---------------------------------#
# 2

d2_1 <- load('data/2_1.RData')
d2_2 <- load('data/2_2.RData')

# relabel p objects
for (i in 1:63){
  
  assign(paste("d2", paste("p", i, sep = ""), sep = "_"), 
         eval(as.symbol(paste("p", i, sep = ""))))
  
}



# create holding DF
out.df.d2 <-  data.frame(
  iter = rep(paste("p", 1:63, sep = ""), each = 11),
  b_c = 2,
  b_h = rep(c(rep(0, 11), rep(0.5, 11), rep(1, 11), rep(1.5, 11), 
              rep(2, 11), rep(2.5, 11), rep(3, 11)), 9),
  n_h = rep(c(rep(1, 77),rep(2, 77), rep(3, 77)), 3),
  alpha = rep(1:11, 63),
  n_strike = c(rep(6, 231), rep(10, 231), rep(15, 231))
)

get_p_results<-function(p,num_alphas)
{
  res=data.frame("post_bias"=rep(NA,num_alphas),
                 "post_mean"=rep(NA,num_alphas),
                 "post_sd"=rep(NA,num_alphas),
                 "post_bias_det80"=rep(NA,num_alphas),
                 "cp_80"=rep(NA,num_alphas),
                 "post_bias_det90"=rep(NA,num_alphas),
                 "cp_90"=rep(NA,num_alphas),
                 "post_bias_det95"=rep(NA,num_alphas),
                 "cp_95"=rep(NA,num_alphas))
  for(i in 1:11)
  {
    res[i,"post_bias"]<-as.numeric(p[[i]][[1]]["post_bias"])
    res[i,"post_mean"]<-as.numeric(p[[i]][[1]]["post_mean"])
    res[i,"post_sd"]<-as.numeric(p[[i]][[1]]["post_sd"])
    res[i,"post_bias_det80"]<-as.numeric(p[[i]][[1]]["post_bias_det80"])
    res[i,"cp_80"]<-as.numeric(p[[i]][[1]]["cp_80"])
    res[i,"post_bias_det90"]<-as.numeric(p[[i]][[1]]["post_bias_det90"])
    res[i,"cp_90"]<-as.numeric(p[[i]][[1]]["cp_90"])
    res[i,"post_bias_det95"]<-as.numeric(p[[i]][[1]]["post_bias_det95"])
    res[i,"cp_95"]<-as.numeric(p[[i]][[1]]["cp_95"])
  }
  return(res)
}

# create list of results
res.l<- list()
whichd  = "d2"
for (j in 1:63){
  iter.ind <- paste(paste(whichd, "p", sep = "_"), j, sep = "")
  iter.ls <- eval(as.symbol(iter.ind))
  print(iter.ind)
  res.l[[j]] <- get_p_results(p = iter.ls,
                              num_alphas = 11)
}

# convert to df
names(res.l) <- paste(paste(whichd, "p", sep = "_"), 1:63, sep = "") 
res.l[["d2_p3"]]
res.df <- do.call(rbind.data.frame, res.l)

# combine with holding df
d2.df <- cbind(out.df.d2, res.df)

#---------------------------------#
# 2.5

d2.5_1 <- load('data/2.5_1.RData')
d2.5_2 <- load('data/2.5_2.RData')

# relabel p objects
for (i in 1:63){
  
  assign(paste("d2.5", paste("p", i, sep = ""), sep = "_"), 
         eval(as.symbol(paste("p", i, sep = ""))))
  
}



# create holding DF
out.df.d2.5 <-  data.frame(
  iter = rep(paste("p", 1:63, sep = ""), each = 11),
  b_c = 2.5,
  b_h = rep(c(rep(0, 11), rep(0.5, 11), rep(1, 11), rep(1.5, 11), 
              rep(2, 11), rep(2.5, 11), rep(3, 11)), 9),
  n_h = rep(c(rep(1, 77),rep(2, 77), rep(3, 77)), 3),
  alpha = rep(1:11, 63),
  n_strike = c(rep(6, 231), rep(10, 231), rep(15, 231))
)

get_p_results<-function(p,num_alphas)
{
  res=data.frame("post_bias"=rep(NA,num_alphas),
                 "post_mean"=rep(NA,num_alphas),
                 "post_sd"=rep(NA,num_alphas),
                 "post_bias_det80"=rep(NA,num_alphas),
                 "cp_80"=rep(NA,num_alphas),
                 "post_bias_det90"=rep(NA,num_alphas),
                 "cp_90"=rep(NA,num_alphas),
                 "post_bias_det95"=rep(NA,num_alphas),
                 "cp_95"=rep(NA,num_alphas))
  for(i in 1:11)
  {
    res[i,"post_bias"]<-as.numeric(p[[i]][[1]]["post_bias"])
    res[i,"post_mean"]<-as.numeric(p[[i]][[1]]["post_mean"])
    res[i,"post_sd"]<-as.numeric(p[[i]][[1]]["post_sd"])
    res[i,"post_bias_det80"]<-as.numeric(p[[i]][[1]]["post_bias_det80"])
    res[i,"cp_80"]<-as.numeric(p[[i]][[1]]["cp_80"])
    res[i,"post_bias_det90"]<-as.numeric(p[[i]][[1]]["post_bias_det90"])
    res[i,"cp_90"]<-as.numeric(p[[i]][[1]]["cp_90"])
    res[i,"post_bias_det95"]<-as.numeric(p[[i]][[1]]["post_bias_det95"])
    res[i,"cp_95"]<-as.numeric(p[[i]][[1]]["cp_95"])
  }
  return(res)
}

# create list of results
res.l<- list()
whichd  = "d2.5"
for (j in 1:63){
  iter.ind <- paste(paste(whichd, "p", sep = "_"), j, sep = "")
  iter.ls <- eval(as.symbol(iter.ind))
  print(iter.ind)
  res.l[[j]] <- get_p_results(p = iter.ls,
                              num_alphas = 11)
}

# convert to df
names(res.l) <- paste(paste(whichd, "p", sep = "_"), 1:63, sep = "") 
res.l[["d2.5_p3"]]
res.df <- do.call(rbind.data.frame, res.l)

# combine with holding df
d2.5.df <- cbind(out.df.d2.5, res.df)

#---------------------------------#
# 3

d3_1 <- load('data/3_1.RData')
d3_2 <- load('data/3_2.RData')

# relabel p objects
for (i in 1:63){
  
  assign(paste("d3", paste("p", i, sep = ""), sep = "_"), 
         eval(as.symbol(paste("p", i, sep = ""))))
  
}



# create holding DF
out.df.d3 <-  data.frame(
  iter = rep(paste("p", 1:63, sep = ""), each = 11),
  b_c = 3,
  b_h = rep(c(rep(0, 11), rep(0.5, 11), rep(1, 11), rep(1.5, 11), 
              rep(2, 11), rep(2.5, 11), rep(3, 11)), 9),
  n_h = rep(c(rep(1, 77),rep(2, 77), rep(3, 77)), 3),
  alpha = rep(1:11, 63),
  n_strike = c(rep(6, 231), rep(10, 231), rep(15, 231))
)

get_p_results<-function(p,num_alphas)
{
  res=data.frame("post_bias"=rep(NA,num_alphas),
                 "post_mean"=rep(NA,num_alphas),
                 "post_sd"=rep(NA,num_alphas),
                 "post_bias_det80"=rep(NA,num_alphas),
                 "cp_80"=rep(NA,num_alphas),
                 "post_bias_det90"=rep(NA,num_alphas),
                 "cp_90"=rep(NA,num_alphas),
                 "post_bias_det95"=rep(NA,num_alphas),
                 "cp_95"=rep(NA,num_alphas))
  for(i in 1:11)
  {
    res[i,"post_bias"]<-as.numeric(p[[i]][[1]]["post_bias"])
    res[i,"post_mean"]<-as.numeric(p[[i]][[1]]["post_mean"])
    res[i,"post_sd"]<-as.numeric(p[[i]][[1]]["post_sd"])
    res[i,"post_bias_det80"]<-as.numeric(p[[i]][[1]]["post_bias_det80"])
    res[i,"cp_80"]<-as.numeric(p[[i]][[1]]["cp_80"])
    res[i,"post_bias_det90"]<-as.numeric(p[[i]][[1]]["post_bias_det90"])
    res[i,"cp_90"]<-as.numeric(p[[i]][[1]]["cp_90"])
    res[i,"post_bias_det95"]<-as.numeric(p[[i]][[1]]["post_bias_det95"])
    res[i,"cp_95"]<-as.numeric(p[[i]][[1]]["cp_95"])
  }
  return(res)
}

# create list of results
res.l<- list()
whichd  = "d3"
for (j in 1:63){
  iter.ind <- paste(paste(whichd, "p", sep = "_"), j, sep = "")
  iter.ls <- eval(as.symbol(iter.ind))
  print(iter.ind)
  res.l[[j]] <- get_p_results(p = iter.ls,
                              num_alphas = 11)
}

# convert to df
names(res.l) <- paste(paste(whichd, "p", sep = "_"), 1:63, sep = "") 
res.l[["d3_p3"]]
res.df <- do.call(rbind.data.frame, res.l)

# combine with holding df
d3.df <- cbind(out.df.d3, res.df)


comb.df <- rbind(d0.df, d0.5.df, d1.df, d1.5.df, 
                 d2.df, d2.5.df, d3.df)




comb.df$alpha.val <- rep(seq(from= 0, to  = 1, by = 0.1), 441)

head(comb.df)
colnames(comb.df)

write.csv(comb.df, "data/simulation_data_all.csv", row.names = FALSE)

#--------------------------------------------------------------#
#--------------------------------------------------------------#

# Plotting 

library(ggplot2)
library(viridis)
library(RColorBrewer)

df.eq <- data.frame(b_h = seq(from = 0, to = 3, by = 0.5), 
                    b_c = seq(from = 0, to = 3, by = 0.5))


# New facet label names for dose variable
hist.labs <- c("N. Historical = 1", "N. Historical = 2", "N. Historical = 3")
names(hist.labs) <- c("1", "2", "3")

# New facet label names for supp variable
alpha.labs <- c("alpha = 0.1", 
                "alpha = 0.5",
                "alpha = 1")
names(alpha.labs) <- c("0.1", "0.5", "1")

pp_15 <- 
  comb.df %>%
  filter(n_strike==15, alpha.val %in% c(0.1, 0.5, 1)) %>%
  ggplot(data = ., aes(x = b_h, y = b_c, fill = post_bias_det95), 
         color="black")+
  geom_tile(color = "black", alpha = 0.9)+
  geom_rect(data = df.eq, aes (xmin = -0.25, xmax = 0.25, 
                               ymin = -0.25, ymax = 0.25),
            color = "black", lwd = 1.2,
            fill = "transparent")+
  coord_equal()+
  geom_text(aes(label = round(post_bias_det95, 2), color = post_bias_det95), 
            size = 2.3, fontface = "bold")+
  scale_color_gradient2(low = "grey35",mid = "grey55", 
                        high = "white", guide = "none")+
  scale_fill_viridis("Bias Detection Rate",direction=-1,
                     option = "inferno", limits = c(0, 1))+
  scale_x_continuous(breaks = c(0:3), expand = c(0,0))+
  scale_y_continuous(breaks = c(0:3), expand = c(0,0))+
  facet_grid(n_h~alpha.val, labeller = labeller(n_h = hist.labs, 
                                                alpha.val = alpha.labs))+
  theme_classic()+
  xlab("Historical Bias")+
  ylab("Current Bias")+
  ggtitle("N Strike = 15")+
  theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        legend.position = "bottom")




pp_10 <- 
  comb.df %>%
  filter(n_strike==10, alpha.val %in% c(0.1, 0.5, 1)) %>%
  ggplot(data = ., aes(x = b_h, y = b_c, fill = post_bias_det95), 
         color="black")+
  geom_tile(color = "black", alpha = 0.9)+
  geom_rect(data = df.eq, aes (xmin = -0.25, xmax = 0.25, 
                               ymin = -0.25, ymax = 0.25),
            color = "black", lwd = 1.2,
            fill = "transparent")+
  coord_equal()+
  geom_text(aes(label = round(post_bias_det95, 2), color = post_bias_det95), 
            size = 2.3, fontface = "bold")+
  scale_color_gradient2(low = "grey35",mid = "grey55", 
                        high = "white", guide = "none")+
  scale_fill_viridis("Bias Detection Rate",direction=-1,
                     option = "inferno", limits = c(0, 1))+
  scale_x_continuous(breaks = c(0:3), expand = c(0,0))+
  scale_y_continuous(breaks = c(0:3), expand = c(0,0))+
  facet_grid(n_h~alpha.val, labeller = labeller(n_h = hist.labs, 
                                                alpha.val = alpha.labs))+
  theme_classic()+
  xlab("Historical Bias")+
  ylab("Current Bias")+
  ggtitle("N Strike = 10")+
  theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        legend.position = "bottom")


pp_6 <- 
  comb.df %>%
  filter(n_strike==6, alpha.val %in% c(0.1, 0.5, 1)) %>%
  ggplot(data = ., aes(x = b_h, y = b_c, fill = post_bias_det95), 
         color="black")+
  geom_tile(color = "black", alpha = 0.9)+
  geom_rect(data = df.eq, aes (xmin = -0.25, xmax = 0.25, 
                               ymin = -0.25, ymax = 0.25),
            color = "black", lwd = 1.2,
            fill = "transparent")+
  coord_equal()+
  geom_text(aes(label = round(post_bias_det95, 2), color = post_bias_det95), 
            size = 2.3, fontface = "bold")+
  scale_color_gradient2(low = "grey35",mid = "grey55", 
                        high = "white", guide = "none")+
  scale_fill_viridis("Bias Detection Rate",direction=-1,
                     option = "inferno", limits = c(0, 1))+
  scale_x_continuous(breaks = c(0:3), expand = c(0,0))+
  scale_y_continuous(breaks = c(0:3), expand = c(0,0))+
  facet_grid(n_h~alpha.val, labeller = labeller(n_h = hist.labs, 
                                                alpha.val = alpha.labs))+
  theme_classic()+
  xlab("Historical Bias")+
  ylab("Current Bias")+
  ggtitle("N Strike = 6")+
  theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        legend.position = "bottom", 
        legend.title.align = -0.5)


ggsave(plot = pp_15, filename = "pp15_95CI.png", height = 8, width = 8, 
       units = "in", dpi = 300)

ggsave(plot = pp_10, filename = "pp10_95CI.png", height = 8, width = 8, 
       units = "in", dpi = 300)

ggsave(plot = pp_6, filename = "pp6_95CI.png", height = 8, width = 8, 
       units = "in", dpi = 300)
