---
title: "Application Outline"
output: 
  github_document:
       pandoc_args: --webtex
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Aim

This application estimates how likely an attorney used peremptory challenges during jury selection to strike potential jurors based on their race or gender. The analysis builds on prior work by @Kadane2018 and @Barrett2007 on statistical analysis for _Batson_ challenges.

## Analysis

To estimate bias, this application relies on two kinds of data: (1) user-inputted data on how an attorney has used strikes in the case before them; and (2) if available, pre-compiled historical data on that attorney's use of strikes in past cases.

In the above plots, $d$ is our measure of bias: **positive** values of $d$ reflect bias _against_ the cognizable class, while **negative** values  of $d$ reflect bias _for_ the cognizable class. If $d$ is exactly **zero**, we can be completely certain that there is zero bias.

Here, we represent $d$ as a distribution of how likely each possible value of $d$ is, given the data we have. This lets us depict how confident we should be in inferring bias from the data we have.

The dashed lines indicate a pre-set _credible interval_, i.e., here the values of $d$ between which 80% of the likely values of $d$ fall. If zero falls within this interval, then we should be wary about (have low confidence in) inferring bias (for or against the cognizable class) from the strike data. If zero falls outside this interval, we should feel confident in inferring bias from the strike data. As we get more data, we should feel more (or less) confident about particular values of $d$.

The grey graph is the distribution of $d$ values based _only_ on a pre-set distribution of $d$ to reflect a starting point that bias is unlikely, as adjusted by historical strike data, if available. This represents our *prior beliefs* about an attorney's possible bias in using peremptory challenges, before we know anything about how any attorney uses peremptory strikes in the case before us. The blue (for prosecution) and red (for the defense) distributions in the foreground represent our _updated_ expectations after accounting for the user-inputted strike data (in the table on the left).

# References